### PR TITLE
Update to canvas-renderer 2.1.0

### PR DESCRIPTION
**Pull request by h0x91b**
got an exception on my production. but this issue is fixed in 2.1.0 version

The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1082797697
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:623:3)
    at Buffer.writeUInt32BE (internal/buffer.js:636:10)
    at PngEncoder_writeTrueColorWithAlpha [as writeTrueColorWithAlpha] (/var/www/x/node_modules/canvas-renderer/lib/png/pngEncoder.js:79:24)
    at Canvas_toPng [as toPng] (/var/www/x/node_modules/canvas-renderer/lib/canvas.js:113:13)
    at Object.toPng (/var/www/x/node_modules/jdenticon/index.js:90:19)
    at Object.generateIcon (/var/www/x/backend/lib/helpers.js:98:27)
    at eval (eval at compile (/var/www/x/node_modules/ejs/lib/ejs.js:618:12), :12:26)

### CODE REVIEW

**Comment by dmester** [comment]
Thank you for the pull request. However it is unlikely that an upgrade from version 2.0.1 to 2.1.0 of canvas-renderer will fix the exception you have encountered. The only change between the two versions is the addition of the method Canvas.toDataURL() which is not used by Jdenticon.

Please create an issue and provide as much information as possible:
* Node.js version and architecture (x86/x64)
* Jdenticon version
* Size and padding of the icon
* Default icon style, or a custom one? Please provide the style configuration if you use a custom style.
* If you can reproduce the exception, sample code is highly appreciated

**Comment by h0x91b** [comment]
```
[WARNING][19-12-2018 13:47:33][child-1] jdenticon throw an exception f135c8463cb69fe35a2df3599fced098bcd5719e 300 RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1082797697
 at checkInt (internal/buffer.js:35:11)
 at writeU_Int32BE (internal/buffer.js:623:3)
 at Buffer.writeUInt32BE (internal/buffer.js:636:10)
 at PngEncoder_writeTrueColorWithAlpha [as writeTrueColorWithAlpha] (/var/www/my-application/node_modules/jdenticon/node_modules/canvas-renderer/lib/png/pngEncoder.js:79:24)
 at Canvas_toPng [as toPng] (/var/www/my-application/node_modules/jdenticon/node_modules/canvas-renderer/lib/canvas.js:113:13)
 at Object.toPng (/var/www/my-application/node_modules/jdenticon/index.js:90:19)
 at Object.generateIcon (/var/www/my-application/backend/lib/helpers.js:100:28)
 at eval (eval at compile (/var/www/my-application/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:12:26)
 at returnedFn (/var/www/my-application/node_modules/ejs/lib/ejs.js:653:17)
 at include (/var/www/my-application/node_modules/ejs/lib/ejs.js:651:39)
 at categories.forEach (eval at compile (/var/www/my-application/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:16:17)
 at Array.forEach (<anonymous>)
 at eval (eval at compile (/var/www/my-application/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:13:19)
 at returnedFn (/var/www/my-application/node_modules/ejs/lib/ejs.js:653:17)
 at include (/var/www/my-application/node_modules/ejs/lib/ejs.js:651:39)
 at eval (eval at compile (/var/www/my-application/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:33:17)
```

Hash is `f135c8463cb69fe35a2df3599fced098bcd5719e`, size = `300`

**Comment by h0x91b** [comment]
Dumped options and rest settings:

```
{
	key: '5c179eb634b3c973b4e71944',
	hash: 'f135c8463cb69fe35a2df3599fced098bcd5719e',
	size: 300,
	options: {
		background: [ 0, 0, 0, 0 ],
		margin: 0.2,
		size: 300,
		format: 'svg'
	},
	error: 'RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1082797697'
}
```

Nodejs -  v10.14.2
NPM - 6.4.1

Tell me if you need something else

**Comment by h0x91b** [comment]
Reproduce:

throws an exception on Cent OS and on my os x both:

```
const jdenticon = require('jdenticon');

const size = 300;
const hash = 'f135c8463cb69fe35a2df3599fced098bcd5719e';  // 15+ hex chars
const options = {
	// foreground: [0, 0, 0, 255],               // rgba black
	background: [0, 0, 0, 0],         // rgba white
	margin: 0.2,                              // 20% margin
	size: size,                                // 420px square
	format: 'svg'                             // use SVG instead of PNG
};

const binary = jdenticon.toPng(hash, size);
base64 = binary.toString('base64');

console.log('base64', base64);
```

**Comment by dmester** [comment]
Thank you for the information. I have reproduced the issue on my machine. The issue seems to occur on Node version 10.x and later due to an API change in the `Buffer` class.

I'm working on a fix for `canvas-renderer` and will release a new version later this week.

**Comment by h0x91b** [comment]
Thanks, I'll wait for the new version, have a nice day.

**Comment by dmester** [comment]
There is now a new release (2.2.1) that should fix this issue. Thanks for your help and have a nice day.

**Pull request closed without merging**
